package rayscal.raw

import scala.scalanative.unsafe.*

@extern
@link("raylib")
object Raylib:
  def InitWindow(width: CInt, height: CInt, title: CString): Unit = extern
  def CloseWindow(): Unit = extern
  def WindowShouldClose(): CBool = extern
  def IsWindowReady(): CBool = extern
  def IsWindowFullscreen(): CBool = extern
  def IsWindowHidden(): CBool = extern
  def IsWindowMinimized(): CBool = extern
  def IsWindowMaximized(): CBool = extern
  def IsWindowFocused(): CBool = extern
  def IsWindowResized(): CBool = extern
  def IsWindowState(flag: CUnsignedInt): CBool = extern
  def SetWindowState(flags: CUnsignedInt): Unit = extern
  def ClearWindowState(flags: CUnsignedInt): Unit = extern
  def ToggleFullscreen(): Unit = extern
  def ToggleBorderlessWindowed(): Unit = extern
  def MaximizeWindow(): Unit = extern
  def MinimizeWindow(): Unit = extern
  def RestoreWindow(): Unit = extern
  def SetWindowTitle(title: CString): Unit = extern
  def SetWindowPosition(x: CInt, y: CInt): Unit = extern
  def SetWindowMonitor(monitor: CInt): Unit = extern
  def SetWindowMinSize(width: CInt, height: CInt): Unit = extern
  def SetWindowMaxSize(width: CInt, height: CInt): Unit = extern
  def SetWindowSize(width: CInt, height: CInt): Unit = extern
  def SetWindowOpacity(opacity: CFloat): Unit = extern
  def SetWindowFocused(): Unit = extern

  def BeginDrawing(): Unit = extern
  def EndDrawing(): Unit = extern
  def ClearBackground(color: Color): Unit = extern
  def BeginMode2D(camera: Camera2D): Unit = extern
  def EndMode2D(): Unit = extern
  def BeginMode3D(camera: Camera3D): Unit = extern
  def EndMode3D(): Unit = extern
  def BeginTextureMode(target: RenderTexture2D): Unit = extern
  def EndTextureMode(): Unit = extern
  def BeginShaderMode(shader: Shader): Unit = extern
  def EndShaderMode(): Unit = extern
  def BeginBlendMode(mode: CInt): Unit = extern
  def EndBlendMode(): Unit = extern
  def BeginScissorMode(x: CInt, y: CInt, width: CInt, height: CInt): Unit = extern
  def EndScissorMode(): Unit = extern

  def DrawText(text: CString, posX: CInt, posY: CInt, fontSize: CInt, color: Color): Unit = extern
  def DrawFPS(posX: CInt, posY: CInt): Unit = extern
  def SetTextLineSpacing(spacing: CInt): Unit = extern
  def MeasureText(text: CString, fontSize: CInt): CInt = extern

  def DrawPixel(posX: CInt, posY: CInt, color: Color): Unit = extern
  def DrawPixelV(position: Vector2, color: Color): Unit = extern
  def DrawLine(startPosX: CInt, startPosY: CInt, endPosX: CInt, endPosY: CInt, color: Color): Unit = extern
  def DrawLineV(startPos: Vector2, endPos: Vector2, color: Color): Unit = extern
  def DrawLineEx(startPos: Vector2, endPos: Vector2, thick: CFloat, color: Color): Unit = extern
  def DrawCircle(centerX: CInt, centerY: CInt, radius: CFloat, color: Color): Unit = extern
  def DrawCircleV(center: Vector2, radius: CFloat, color: Color): Unit = extern
  def DrawCircleLines(centerX: CInt, centerY: CInt, radius: CFloat, color: Color): Unit = extern
  def DrawEllipse(centerX: CInt, centerY: CInt, radiusH: CFloat, radiusV: CFloat, color: Color): Unit = extern
  def DrawEllipseLines(centerX: CInt, centerY: CInt, radiusH: CFloat, radiusV: CFloat, color: Color): Unit = extern
  def DrawRing(center: Vector2, innerRadius: CFloat, outerRadius: CFloat, startAngle: CFloat, endAngle: CFloat, segments: CInt, color: Color): Unit = extern
  def DrawRectangle(posX: CInt, posY: CInt, width: CInt, height: CInt, color: Color): Unit = extern
  def DrawRectangleV(position: Vector2, size: Vector2, color: Color): Unit = extern
  def DrawRectangleRec(rec: Rectangle, color: Color): Unit = extern
  def DrawRectangleLines(posX: CInt, posY: CInt, width: CInt, height: CInt, color: Color): Unit = extern
  def DrawRectangleLinesEx(rec: Rectangle, lineThick: CFloat, color: Color): Unit = extern
  def DrawTriangle(v1: Vector2, v2: Vector2, v3: Vector2, color: Color): Unit = extern
  def DrawTriangleLines(v1: Vector2, v2: Vector2, v3: Vector2, color: Color): Unit = extern
  def DrawPoly(center: Vector2, sides: CInt, radius: CFloat, rotation: CFloat, color: Color): Unit = extern
  def DrawPolyLines(center: Vector2, sides: CInt, radius: CFloat, rotation: CFloat, color: Color): Unit = extern
  def DrawPolyLinesEx(center: Vector2, sides: CInt, radius: CFloat, rotation: CFloat, lineThick: CFloat, color: Color): Unit = extern

  def SetTargetFPS(fps: CInt): Unit = extern
  def GetFrameTime(): CFloat = extern
  def GetTime(): CDouble = extern
  def GetFPS(): CInt = extern
  def GetScreenWidth(): CInt = extern
  def GetScreenHeight(): CInt = extern
  def GetRenderWidth(): CInt = extern
  def GetRenderHeight(): CInt = extern
  def SetRandomSeed(seed: CUnsignedInt): Unit = extern
  def GetRandomValue(min: CInt, max: CInt): CInt = extern
  def TakeScreenshot(fileName: CString): Unit = extern
  def SetConfigFlags(flags: CUnsignedInt): Unit = extern
  def SetTraceLogLevel(logLevel: CInt): Unit = extern

  def IsKeyDown(key: CInt): CBool = extern
  def IsKeyPressed(key: CInt): CBool = extern
  def IsKeyPressedRepeat(key: CInt): CBool = extern
  def IsKeyReleased(key: CInt): CBool = extern
  def IsKeyUp(key: CInt): CBool = extern
  def GetKeyPressed(): CInt = extern
  def GetCharPressed(): CInt = extern
  def SetExitKey(key: CInt): Unit = extern

  def IsMouseButtonPressed(button: CInt): CBool = extern
  def IsMouseButtonDown(button: CInt): CBool = extern
  def IsMouseButtonReleased(button: CInt): CBool = extern
  def IsMouseButtonUp(button: CInt): CBool = extern
  def GetMouseX(): CInt = extern
  def GetMouseY(): CInt = extern
  def GetMousePosition(): Vector2 = extern
  def GetMouseDelta(): Vector2 = extern
  def SetMousePosition(x: CInt, y: CInt): Unit = extern
  def SetMouseOffset(offsetX: CInt, offsetY: CInt): Unit = extern
  def SetMouseScale(scaleX: CFloat, scaleY: CFloat): Unit = extern
  def GetMouseWheelMove(): CFloat = extern
  def GetMouseWheelMoveV(): Vector2 = extern
  def SetMouseCursor(cursor: CInt): Unit = extern
  def ShowCursor(): Unit = extern
  def HideCursor(): Unit = extern
  def IsCursorHidden(): CBool = extern
  def EnableCursor(): Unit = extern
  def DisableCursor(): Unit = extern
  def IsCursorOnScreen(): CBool = extern

  def LoadImage(fileName: CString): Image = extern
  def GenImageColor(width: CInt, height: CInt, color: Color): Image = extern
  def GenImageChecked(width: CInt, height: CInt, checksX: CInt, checksY: CInt, col1: Color, col2: Color): Image = extern
  def IsImageValid(image: Image): CBool = extern
  def UnloadImage(image: Image): Unit = extern
  def ExportImage(image: Image, fileName: CString): CBool = extern

  def LoadTexture(fileName: CString): Texture2D = extern
  def LoadTextureFromImage(image: Image): Texture2D = extern
  def LoadRenderTexture(width: CInt, height: CInt): RenderTexture2D = extern
  def IsTextureValid(texture: Texture2D): CBool = extern
  def UnloadTexture(texture: Texture2D): Unit = extern
  def IsRenderTextureValid(target: RenderTexture2D): CBool = extern
  def UnloadRenderTexture(target: RenderTexture2D): Unit = extern
  def SetTextureFilter(texture: Texture2D, filter: CInt): Unit = extern
  def SetTextureWrap(texture: Texture2D, wrap: CInt): Unit = extern
  def DrawTexture(texture: Texture2D, posX: CInt, posY: CInt, tint: Color): Unit = extern
  def DrawTextureV(texture: Texture2D, position: Vector2, tint: Color): Unit = extern
  def DrawTextureEx(texture: Texture2D, position: Vector2, rotation: CFloat, scale: CFloat, tint: Color): Unit = extern
  def DrawTextureRec(texture: Texture2D, source: Rectangle, position: Vector2, tint: Color): Unit = extern
  def DrawTexturePro(texture: Texture2D, source: Rectangle, dest: Rectangle, origin: Vector2, rotation: CFloat, tint: Color): Unit = extern

  def LoadShader(vsFileName: CString, fsFileName: CString): Shader = extern
  def LoadShaderFromMemory(vsCode: CString, fsCode: CString): Shader = extern
  def IsShaderValid(shader: Shader): CBool = extern
  def GetShaderLocation(shader: Shader, uniformName: CString): CInt = extern
  def GetShaderLocationAttrib(shader: Shader, attribName: CString): CInt = extern
  def SetShaderValue(shader: Shader, locIndex: CInt, value: Ptr[Byte], uniformType: CInt): Unit = extern
  def SetShaderValueV(shader: Shader, locIndex: CInt, value: Ptr[Byte], uniformType: CInt, count: CInt): Unit = extern
  def SetShaderValueMatrix(shader: Shader, locIndex: CInt, mat: Matrix): Unit = extern
  def SetShaderValueTexture(shader: Shader, locIndex: CInt, texture: Texture2D): Unit = extern
  def UnloadShader(shader: Shader): Unit = extern

  def GetScreenToWorldRay(position: Vector2, camera: Camera): Ray = extern
  def GetScreenToWorldRayEx(position: Vector2, camera: Camera, width: CInt, height: CInt): Ray = extern
  def GetWorldToScreen(position: Vector3, camera: Camera): Vector2 = extern
  def GetWorldToScreenEx(position: Vector3, camera: Camera, width: CInt, height: CInt): Vector2 = extern
  def GetWorldToScreen2D(position: Vector2, camera: Camera2D): Vector2 = extern
  def GetScreenToWorld2D(position: Vector2, camera: Camera2D): Vector2 = extern
  def GetCameraMatrix(camera: Camera): Matrix = extern
  def GetCameraMatrix2D(camera: Camera2D): Matrix = extern

  def ColorIsEqual(col1: Color, col2: Color): CBool = extern
  def Fade(color: Color, alpha: CFloat): Color = extern
  def ColorToInt(color: Color): CInt = extern
  def ColorNormalize(color: Color): Vector4 = extern
  def ColorFromNormalized(normalized: Vector4): Color = extern
  def ColorToHSV(color: Color): Vector3 = extern
  def ColorFromHSV(hue: CFloat, saturation: CFloat, value: CFloat): Color = extern
  def ColorTint(color: Color, tint: Color): Color = extern
  def ColorBrightness(color: Color, factor: CFloat): Color = extern

  def CheckCollisionRecs(rec1: Rectangle, rec2: Rectangle): CBool = extern
  def CheckCollisionCircles(center1: Vector2, radius1: CFloat, center2: Vector2, radius2: CFloat): CBool = extern
  def CheckCollisionCircleRec(center: Vector2, radius: CFloat, rec: Rectangle): CBool = extern
  def CheckCollisionPointRec(point: Vector2, rec: Rectangle): CBool = extern
  def CheckCollisionPointCircle(point: Vector2, center: Vector2, radius: CFloat): CBool = extern
  def CheckCollisionPointTriangle(point: Vector2, p1: Vector2, p2: Vector2, p3: Vector2): CBool = extern
  def GetCollisionRec(rec1: Rectangle, rec2: Rectangle): Rectangle = extern

  def DrawLine3D(startPos: Vector3, endPos: Vector3, color: Color): Unit = extern
  def DrawPoint3D(position: Vector3, color: Color): Unit = extern
  def DrawCircle3D(center: Vector3, radius: CFloat, rotationAxis: Vector3, rotationAngle: CFloat, color: Color): Unit = extern
  def DrawTriangle3D(v1: Vector3, v2: Vector3, v3: Vector3, color: Color): Unit = extern
  def DrawCube(position: Vector3, width: CFloat, height: CFloat, length: CFloat, color: Color): Unit = extern
  def DrawCubeV(position: Vector3, size: Vector3, color: Color): Unit = extern
  def DrawCubeWires(position: Vector3, width: CFloat, height: CFloat, length: CFloat, color: Color): Unit = extern
  def DrawCubeWiresV(position: Vector3, size: Vector3, color: Color): Unit = extern
  def DrawSphere(centerPos: Vector3, radius: CFloat, color: Color): Unit = extern
  def DrawSphereEx(centerPos: Vector3, radius: CFloat, rings: CInt, slices: CInt, color: Color): Unit = extern
  def DrawSphereWires(centerPos: Vector3, radius: CFloat, rings: CInt, slices: CInt, color: Color): Unit = extern
  def DrawCylinder(position: Vector3, radiusTop: CFloat, radiusBottom: CFloat, height: CFloat, slices: CInt, color: Color): Unit = extern
  def DrawCylinderEx(startPos: Vector3, endPos: Vector3, startRadius: CFloat, endRadius: CFloat, sides: CInt, color: Color): Unit = extern
  def DrawCylinderWires(position: Vector3, radiusTop: CFloat, radiusBottom: CFloat, height: CFloat, slices: CInt, color: Color): Unit = extern
  def DrawCylinderWiresEx(startPos: Vector3, endPos: Vector3, startRadius: CFloat, endRadius: CFloat, sides: CInt, color: Color): Unit = extern
  def DrawCapsule(startPos: Vector3, endPos: Vector3, radius: CFloat, slices: CInt, rings: CInt, color: Color): Unit = extern
  def DrawCapsuleWires(startPos: Vector3, endPos: Vector3, radius: CFloat, slices: CInt, rings: CInt, color: Color): Unit = extern
  def DrawPlane(centerPos: Vector3, size: Vector2, color: Color): Unit = extern
  def DrawRay(ray: Ray, color: Color): Unit = extern
  def DrawGrid(slices: CInt, spacing: CFloat): Unit = extern
  def CheckCollisionSpheres(center1: Vector3, radius1: CFloat, center2: Vector3, radius2: CFloat): CBool = extern
  def CheckCollisionBoxes(box1: BoundingBox, box2: BoundingBox): CBool = extern
  def CheckCollisionBoxSphere(box: BoundingBox, center: Vector3, radius: CFloat): CBool = extern
  def GetRayCollisionSphere(ray: Ray, center: Vector3, radius: CFloat): RayCollision = extern
  def GetRayCollisionBox(ray: Ray, box: BoundingBox): RayCollision = extern
  def GetRayCollisionTriangle(ray: Ray, p1: Vector3, p2: Vector3, p3: Vector3): RayCollision = extern
  def GetRayCollisionQuad(ray: Ray, p1: Vector3, p2: Vector3, p3: Vector3, p4: Vector3): RayCollision = extern

  def InitAudioDevice(): Unit = extern
  def CloseAudioDevice(): Unit = extern
  def IsAudioDeviceReady(): CBool = extern
  def SetMasterVolume(volume: CFloat): Unit = extern
  def GetMasterVolume(): CFloat = extern
  def LoadWave(fileName: CString): Wave = extern
  def IsWaveValid(wave: Wave): CBool = extern
  def LoadSound(fileName: CString): Sound = extern
  def LoadSoundFromWave(wave: Wave): Sound = extern
  def LoadSoundAlias(source: Sound): Sound = extern
  def IsSoundValid(sound: Sound): CBool = extern
  def UnloadWave(wave: Wave): Unit = extern
  def UnloadSound(sound: Sound): Unit = extern
  def UnloadSoundAlias(alias: Sound): Unit = extern
  def PlaySound(sound: Sound): Unit = extern
  def StopSound(sound: Sound): Unit = extern
  def PauseSound(sound: Sound): Unit = extern
  def ResumeSound(sound: Sound): Unit = extern
  def IsSoundPlaying(sound: Sound): CBool = extern
  def SetSoundVolume(sound: Sound, volume: CFloat): Unit = extern
  def SetSoundPitch(sound: Sound, pitch: CFloat): Unit = extern
  def SetSoundPan(sound: Sound, pan: CFloat): Unit = extern
  def LoadMusicStream(fileName: CString): Music = extern
  def IsMusicValid(music: Music): CBool = extern
  def UnloadMusicStream(music: Music): Unit = extern
  def PlayMusicStream(music: Music): Unit = extern
  def IsMusicStreamPlaying(music: Music): CBool = extern
  def UpdateMusicStream(music: Music): Unit = extern
  def StopMusicStream(music: Music): Unit = extern
  def PauseMusicStream(music: Music): Unit = extern
  def ResumeMusicStream(music: Music): Unit = extern
  def SeekMusicStream(music: Music, position: CFloat): Unit = extern
  def SetMusicVolume(music: Music, volume: CFloat): Unit = extern
  def SetMusicPitch(music: Music, pitch: CFloat): Unit = extern
  def SetMusicPan(music: Music, pan: CFloat): Unit = extern
  def GetMusicTimeLength(music: Music): CFloat = extern
  def GetMusicTimePlayed(music: Music): CFloat = extern
